//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Pizzatorium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDelivery
    {
        public string dName { get; set; }
        public string dArea { get; set; }
        public string dPhoto { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
