//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Pizzatorium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredient
    {
        public string dIngredient { get; set; }
        public string dCost { get; set; }
    }
}
