//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Pizzatorium.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class The_PizzatoriumEntities2 : DbContext
    {
        public The_PizzatoriumEntities2()
            : base("name=The_PizzatoriumEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArea> tblAreas { get; set; }
        public virtual DbSet<tblDelivery> tblDeliveries { get; set; }
        public virtual DbSet<tblIngredient> tblIngredients { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
